### ISSUE TITLE
Add the possibility to set the "Recordings Location" by calling the new embedded SailFish2 File Manager

### ISSUE THREAD

**Issue by sebma** [cornedor/sailfish-recorder#12]
Hi,

Can you add the possibility to set the "Recordings Location" by calling the new embedded SailFish2 File Manager ?

You can look at the [last picture](https://cdn-blog.jolla.com/wp-content/uploads/2016/09/Screenshot_20160926_002.png) from [Sailfish OS Fiskarsinjoki available now](https://blog.jolla.com/fiskarsinjoki/) to see what I'm talking about.

Thanks for your time.

**Comment by cornedor** [comment]
Hey, I'll look at it if that is possible or if that is something that is not allowed in in the Jolla Store

**Comment by mentaljam** [comment]
The new beta SDK provides Sailfish.Pickers types but as I can see there is no ability to select a folder.
