### ISSUE TITLE
audio compressor details

### ISSUE THREAD

**Issue by m00ny** [cornedor/sailfish-recorder#2]
Hi cornedor,

please give us details about the audio compressor that's used (at least with codec flac). Maybe the compression happens before sailfish-recorder, then nevermind.
I'm trying to get at least a bit compression out of a recording, using an expander, but I can't figure out the right settings for it.

Best regards, great app anyway :)
m00ny

**Comment by cornedor** [comment]
Hey,

I'm using the QAudioRecorder and QAudioEncoderSettings classes from Qt. There is were all the encoding etc is done. I'm sorry, but I don't know too much about that.

I hope you can find a solution.

Corné
