### ISSUE TITLE
Add a pause button to the player

### ISSUE THREAD

**Issue by sebma** [cornedor/sailfish-recorder#3]
Hi,

Your player is not (yet :) ) able to pause when playing a file previously recorded.

So I try to Open the file inside the sailfish file browser, but it says:

"No application to open the file:
xdg-open found no preferred application"

I'm using Sailfish OS 2.0.0.10.

Can you add the pause functionality ?

Or even better, can you add a bar to go to a specific position inside the recorded file ?

Sébastien.

**Comment by cornedor** [comment]
Thanks for the suggestion, I'll try to at least add a pause button when I have some time
